-- Seed data for Florante Hackathon System

INSERT INTO hackathons (
  title, 
  description, 
  tagline, 
  longDescription, 
  objectives, 
  rules, 
  prizes, 
  schedule, 
  judges, 
  sponsors, 
  techStack, 
  prize_pool_desc, 
  start_date, 
  deadline, 
  status
) VALUES 
(
  'Global AI Hackathon 2026',
  'Build the next generation of AI-powered applications to solve real-world problems.',
  'Shape the Future with Artificial Intelligence',
  'Join thousands of developers worldwide in the largest AI-focused hackathon. Build groundbreaking AI applications that solve real-world challenges in healthcare, education, sustainability, and beyond.',
  '["Develop innovative AI solutions", "Create scalable applications", "Learn from industry experts"]'::jsonb,
  'All code must be original. Teams of 2-6 members. Submissions require GitHub repo and demo video.',
  '[{"place": "1st Place", "amount": "$25,000", "perks": "Mentorship with Google AI"}, {"place": "2nd Place", "amount": "$15,000", "perks": "Fast-track to AI Accelerator"}]'::jsonb,
  '[{"day": "Day 1", "date": "2026-04-15", "activity": "Kickoff"}, {"day": "Day 3", "date": "2026-04-17", "activity": "Deadline"}]'::jsonb,
  '[{"name": "Dr. Sarah Chen", "role": "AI Director", "company": "Google AI"}]'::jsonb,
  '["Google AI", "Microsoft", "OpenAI"]'::jsonb,
  '["Python", "TensorFlow", "PyTorch", "Docker"]'::jsonb,
  'Over $100,000 in prizes and opportunities',
  '2026-04-15 10:00:00+00',
  '2026-04-22 23:59:59+00',
  'Ongoing'
),
(
  'Web3 Innovators Challenge',
  'Create decentralized solutions for finance, gaming, and identity.',
  'Build the Decentralized Future',
  'In partnership with leading blockchain foundations, this hackathon challenges developers to push the boundaries of Web3 technology.',
  '["Build production-ready dApps", "Implement tokenomics", "Cross-chain integration"]'::jsonb,
  'Smart contracts must be on testnet. Open-source preferred. Teams of 2-5.',
  '[{"place": "1st Place", "amount": "$50,000", "perks": "VC funding opportunity"}]'::jsonb,
  '[{"day": "Registration", "date": "2026-05-01", "activity": "Team Formation"}]'::jsonb,
  '[{"name": "Vitalik Buterin", "role": "Co-founder", "company": "Ethereum"}]'::jsonb,
  '["Ethereum", "Solana", "Polygon"]'::jsonb,
  '["Solidity", "Rust", "TypeScript", "IPFS"]'::jsonb,
  'Huge prize pool for the next Web3 unicorns',
  '2026-05-10 09:00:00+00',
  '2026-05-30 23:59:59+00',
  'Upcoming'
),
(
  'Sustainable Tech Summit',
  'Develop innovative solutions for climate change and renewable energy.',
  'Innovation for a Greener Planet',
  'Join the movement to save our planet using technology. We are looking for solutions in solar energy, waste management, and carbon capture.',
  '["Reduce carbon footprint", "Renewable energy tracking", "Eco-friendly supply chains"]'::jsonb,
  'Hardware and software projects allowed. Teams of 1-4.',
  '[{"place": "1st Place", "amount": "$30,000", "perks": "Green Tech Grant"}]'::jsonb,
  '[{"day": "Workshop", "date": "2026-06-05", "activity": "Sustainability in Tech"}]'::jsonb,
  '[{"name": "Jane Goodall", "role": "Environmentalist", "company": "Roots & Shoots"}]'::jsonb,
  '["Tesla", "Greenpeace", "SolarCity"]'::jsonb,
  '["IoT", "React", "Python", "LoRaWAN"]'::jsonb,
  'Funding and support for sustainable startups',
  '2026-06-15 08:00:00+00',
  '2026-06-25 18:00:00+00',
  'Upcoming'
);
